# Generated by Django 5.1 on 2024-08-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fle',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
