# Generated by Django 5.1 on 2025-01-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('essential', 'Essential'), ('premium', 'Premium'), ('ultimate', 'Ultimate')], max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('features', models.JSONField(default=list)),
                ('max_users', models.PositiveIntegerField()),
                ('allowed_apps', models.JSONField(default=list)),
            ],
        ),
    ]
