# Generated by Django 5.1 on 2024-10-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_tenant_group_subscription_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='user',
        ),
        migrations.AddField(
            model_name='license',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='license.group'),
        ),
    ]
