# Generated by Django 5.1 on 2024-10-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_remove_subscription_allowed_apps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
