# Generated by Django 5.1 on 2024-10-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0008_remove_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='allowed_apps',
            field=models.JSONField(default=list),
        ),
    ]
